# Generated by Django 6.0.1 on 2026-01-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="full_name",
            new_name="name",
        ),
    ]
