# Generated by Django 6.0.1 on 2026-02-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_rename_full_name_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller"), ("admin", "Admin")],
                default="buyer",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
