# Generated by Django 6.0.1 on 2026-02-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_account_is_active_account_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
